### ISSUE TITLE
ncclCommInitRankMulti has been deprecated in RCCL but still exists in RCCL tests

### ISSUE THREAD

**Issue by baiwei0427** [ROCm/rccl-tests#53]
If we compile RCCL tests with the latest RCCL, it will report error "ld.lld: error: undefined symbol: ncclCommInitRankMulti".

**Comment by nileshnegi** [comment]
@baiwei0427 do you still observe this error?

**Comment by ppanchad-amd** [comment]
Hi @baiwei0427. Closing ticket due to lack of activity. Please feel free to re-open ticket if you still see the issue with the latest ROCm. Thanks!
